# Setup
title:        
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        jyj-jeong.github.io
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
